### ISSUE TITLE
Initializing shadcn requires index.css instead of index.scss

### ISSUE THREAD

**Issue by vest-dk** [Manta-Network/react-dapp-starter#9]
After running `npx shadcn@latest init`, I got the following error:

```
git:(main) ✗ npx shadcn@latest init 

✔ Preflight checks.
✔ Verifying framework. Found Remix.
✖ Validating Tailwind CSS.
✔ Validating import alias.

No Tailwind CSS configuration found at /Users/dankim/Desktop/vest/revamp/vest-frontend.
It is likely you do not have Tailwind CSS installed or have an invalid configuration.
Install Tailwind CSS then try again.
Visit https://tailwindcss.com/docs/guides/remix to get started.
```

After changing the index.scss file to .css, the init command worked. Is it okay to turn the extension back to .scss after initializing?

**Comment by jasonintju** [comment]
You don't need init shadcn again in this template. But anyway, you can use `.css` first, then turn back to `.scss` after initializing.
